package com.betterrtp.config;

/** Every user-facing message key. The config path is derived: CANCELLED_MOVE -> messages.cancelled-move. */
public enum Msg {
    NO_PERMISSION, PLAYER_ONLY, COOLDOWN, ALREADY_IN_PROGRESS,
    COUNTDOWN_ACTIONBAR, COUNTDOWN_TITLE, COUNTDOWN_SUBTITLE, COUNTDOWN_BOSSBAR,
    SEARCHING, QUEUED, BUSY,
    CANCELLED_MOVE, CANCELLED_DAMAGE, CANCELLED_WORLD, CANCELLED_WORLD_UNLOADED, CANCELLED_RELOAD,
    TELEPORT_SUCCESS, SEARCH_FAILED, TELEPORT_FAILED,
    INVALID_WORLD, WORLD_DISABLED, WORLD_UNAVAILABLE, DESTINATION_UNAVAILABLE,
    INVALID_BIOME, BIOME_DISABLED, BEDROCK_UNAVAILABLE, CONFIG_ERROR,
    RELOAD_SUCCESS, RELOAD_FAILURE, RTPGUI_DISABLED, USAGE, HELP;

    public String path() { return "messages." + name().toLowerCase(java.util.Locale.ROOT).replace('_', '-'); }
}
